name: CD

on:
    workflow_run:
        workflows: ["CI"]
        types: [completed]

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        permissions:
            actions: read

        steps:
            # Download the build artifact from the CI run that triggered this
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: deploy
                  path: deploy
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  run-id: ${{ github.event.workflow_run.id }}

            # Install Netlify CLI
            - name: Install Netlify CLI
              run: npm install -g netlify-cli
            
            - name: List artifact files (debug)
              run: |
                ls -la deploy
                ls -la deploy/dist
                ls -la deploy/scripts
                ls -la deploy/netlify
                ls -la deploy/netlify/functions
            
            # Verify and make deployment scripts executable
            - name: Verify and prepare deployment scripts
              run: |
                if [ ! -f "deploy/scripts/check-cd-secrets.sh" ] || [ ! -f "deploy/scripts/deploy-to-netlify.sh" ]; then
                  echo "Error: Required deployment scripts not found"
                  exit 1
                fi
                chmod +x deploy/scripts/*.sh
            
            # Deploy to Netlify
            - name: Deploy to Netlify
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  PROD_SITE: ${{ secrets.NETLIFY_SITE_ID }}
                  BETA_SITE: ${{ secrets.BETA_NETLIFY_SITE_ID }}
                  BRANCH: ${{ github.event.workflow_run.head_branch }}
              run: |
                # Verify secrets first
                ./deploy/scripts/check-cd-secrets.sh
                # Run deployment
                ./deploy/scripts/deploy-to-netlify.sh
