name: CD

# Event Triggers
on:
    # Trigger CD when CI workflow is completed
    workflow_run:
        workflows: ["CI"]
        types: ["completed"]
        branches: ["master"]

jobs:
    # Deploy Job
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        # Grant read permission to the actions scope for this job
        permissions:
            actions: read

        steps:
            # Download build artifact from CI workflow
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  run-id: ${{ github.event.workflow_run.id }}

            # Install Netlify CLI
            - name: Install Netlify CLI
              run: npm install -g netlify-cli

            # Deploy to Netlify
            - name: Deploy to Netlify
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              run: |
                  netlify deploy \
                  --dir=dist \
                  --site=$NETLIFY_SITE_ID \
                  --auth=$NETLIFY_AUTH_TOKEN \
                  --prod
