name: CD

on:
    workflow_run:
        workflows: ["CI"]
        types: [completed]

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        permissions:
            actions: read

        steps:
            # Download the build artifact from the CI run that triggered this
            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  repository: ${{ github.repository }}
                  run-id: ${{ github.event.workflow_run.id }}

            # Install Netlify CLI
            - name: Install Netlify CLI
              run: npm install -g netlify-cli

            # Deploy to Netlify
            - name: Deploy to Netlify
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  PROD_SITE: ${{ secrets.NETLIFY_SITE_ID }}
                  BETA_SITE: ${{ secrets.BETA_NETLIFY_SITE_ID }}
              run: |
                  BRANCH="${{ github.event.workflow_run.head_branch }}"
                  echo "Triggered by branch: $BRANCH"

                  if [ "$BRANCH" = "master" ]; then
                    echo "Deploying to PRODUCTION site..."
                    netlify deploy \
                      --dir=dist \
                      --site=$PROD_SITE \
                      --auth=$NETLIFY_AUTH_TOKEN \
                      --prod
                  else
                    echo "Deploying to BETA site..."
                    netlify deploy \
                      --dir=dist \
                      --site=$BETA_SITE \
                      --auth=$NETLIFY_AUTH_TOKEN \
                      --prod
                  fi
