name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Setup bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: "latest"
            
            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Run ESLint
              run: bun dev lint
            
            - name: Type Check
              run: bunx tsc --noEmit
            
            - name: Build
              run: bun dev build
            
            - name: Upload production-ready build
              uses: actions/upload-artifact@v4
              with:
                name: dist
                path: dist
            



            